name: Build and Deployment  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1 
    - name: Restore packages
      run: nuget restore dotnetFramework-demo.sln
      
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1 
    - name: Build with MSBuild
      run:
        msbuild dotnetFramework-demo.sln /p:Configuration=Release
    - name: 'Upload Package'
      uses: actions/upload-artifact@v1
      with:
        name: BuildArtifacts
        path: dotnetFramework-demo
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
       app-name: vsdotnetframeworkapp-demo
       publish-profile: ${{ secrets.publish_profile }}
    # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
       package: dotnetFramework-demo
    
    
